add tabs
pozdnyakoks/AdvancedJS pull request #2
Opened 2023-02-09 20:36 UTC by pozdnyakoks

2023-02-09 20:41 UTC, pozdnyakoks commented
если смотреть на разрешении 1120, секция с остеклением, при проматывании вправо табы с остеклением перестают меняться, показывает только деревянное, откликается только французское остекление (влево все работает)

2023-02-10 06:15 UTC, andrey-kudinov requested changes
Мне очень понравился стиль твоего кода
Ты круто всё сделала 👍
Я написал несколько моментов как можно ещё улучшить

Так же я заметил что при навигации с клавиатуры я могу переключаться между табами, но не могу его открыть клавишей `enter`

Сделай пж чтобы открывалось не только по клику, но и по клавише en`t`er

2023-02-10 06:15 UTC, andrey-kudinov commented on src/js/main.js
> +  tabs('.decoration_slider', '.no_click', '.decoration_content > div > div', 'after_click')
Старайся пж не использовать в функции больше 2-3 аргументов
Это делает её сложной в использовании
Особенно, если часть аргументов опциональные
Так же для стороннего человека будет не понятно для чего все эти аргументы
Если вложить объект как аргумент, станет всё значительно читабельнее

Материал по этому вопросу (2-3 минуты):
https://github.com/ryanmcdermott/clean-code-javascript#function-arguments-2-or-fewer-ideally

2023-02-10 06:15 UTC, andrey-kudinov commented on src/js/main.js
> +import tabs from './modules/tabs'
Я бы советовал в директории `modules` создать `index.js` и в нём собрать все импорты, чтобы из него экспортировать

Для дефолтных экспортов

```
// index.js
export { default } from './modals.js'
export { default } from './tabs.js'
```
Для именных импортов (мне больше нрав именные, они лучше поддерживаются редактором)

```
// index.js
export { modals } from './modals.js'
export { tabs } from './tabs.js'
```
Тогда в главном файле не будет большой портянки импортов
По мере роста проекта она бы увеличилась, лучше подумать об этом уже сейчас

```
// main.js
import { modals, tabs } from "./modules
```

**ПРИМЕРЫ**

Пример как будет здорово 
```
// main.js
import { modals, tabs, тут-что-нб, ещё-что-нб, и-ещё } from "./modules
```

Как не здорово на мой взгляд
```
// main.js
import { modals, tabs, тут-что-нб, ещё-что-нб, и-ещё } from "./modules
import modals from './modules/modals';
import тут-что-нб from './modules/тут-что-нб'
iport ещё-что-нб from './modules/ещё-что-нб';
import и-ещё from './modules/и-ещё'
```

У такого подхода даже есть малоизвестное название - [принцип/система barrel](https://basarat.gitbook.io/typescript/main-1/barrel)

2023-02-10 06:15 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +export default tabsFunction;
Оставляй пж к конце файла одну пустую строчку
Считается хорошим тоном)
Вроде мелочь, но даже линтеры настраивают на проектах к таким правилам

2023-02-10 06:21 UTC, andrey-kudinov commented
> если смотреть на разрешении 1120, секция с остеклением, при проматывании вправо табы с остеклением перестают меняться, показывает только деревянное, откликается только французское остекление (влево все работает)

Я думаю из-за слик-слайдера ошибка
Он создаёт новые слайды, а не переносит старые
Из-за этого для 5 слайдов у него 10 блоков
А события по всей видимости у нас висят только на первых 5 блоках
<img width="720" alt="image" src="https://user-images.githubusercontent.com/64890665/218017929-7aee6192-3b0c-4ebf-a6a0-57bcd39e691f.png">

2023-02-10 14:16 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +    if (ev.keyCode == 13) {
`keyKode` устарел
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

Используй пж `code`
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

2023-02-10 14:16 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +const tabsFunction = ({ headerSelector, tabsSelector, contentsSelector, activeClass }) => {
Ты можешь использовать
`export tabs = ...`
прямо тут

Чтобы сразу было понятно что именно экспортируется
Особенно это полезно будет в крупных файлах

2023-02-10 15:24 UTC, merged